language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements/development.txt
script:
    - make test
notifications:
  slack: gruteogisu:ckKmvAuRsvISkXP1kFyTXjSH
